// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAtK7pClBHQ3zemIy7LbgteIr2WIGKHGs',
    appId: '1:364751457506:web:d5cb5e34b127144d0ca2bb',
    messagingSenderId: '364751457506',
    projectId: 'recipesharing-44c6f',
    authDomain: 'recipesharing-44c6f.firebaseapp.com',
    storageBucket: 'recipesharing-44c6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8wusCiECJElhvqXSlM5_kBkntE29lKog',
    appId: '1:364751457506:android:269292da22ffe5520ca2bb',
    messagingSenderId: '364751457506',
    projectId: 'recipesharing-44c6f',
    storageBucket: 'recipesharing-44c6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYbAn1bsZ6BXGzFPwqXBZXIR1M8ovUFSY',
    appId: '1:364751457506:ios:79054bd6d51e522a0ca2bb',
    messagingSenderId: '364751457506',
    projectId: 'recipesharing-44c6f',
    storageBucket: 'recipesharing-44c6f.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYbAn1bsZ6BXGzFPwqXBZXIR1M8ovUFSY',
    appId: '1:364751457506:ios:79054bd6d51e522a0ca2bb',
    messagingSenderId: '364751457506',
    projectId: 'recipesharing-44c6f',
    storageBucket: 'recipesharing-44c6f.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAtK7pClBHQ3zemIy7LbgteIr2WIGKHGs',
    appId: '1:364751457506:web:137c444f86d6cb2a0ca2bb',
    messagingSenderId: '364751457506',
    projectId: 'recipesharing-44c6f',
    authDomain: 'recipesharing-44c6f.firebaseapp.com',
    storageBucket: 'recipesharing-44c6f.firebasestorage.app',
  );
}
